version: '3'
services:
  api:
    # depends_on:
    #   - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - WEB_URL=http://localhost:3000
      - MONGO_URI=mongodb+srv://vtrGuerra:flamengo81@cluster0.gi3tf.mongodb.net/Warriors?retryWrites=true&w=majority
      - DB_NAME=gerenciamento-estoque
      - EMAIL=suporte.abclivros@gmail.com
      - EMAIL_PASSWORD=livros2122
      - JWT_SECRET=uyrxvzhjnkgvwquaisdozjn2qwdasxz
      - COMPANY_NAME=ABC Livros e Brinquedos
      - FACEBOOK_URL=https://pt-br.facebook.com/www.abclivrosebrinquedos.com.br/
      - CENTRAL_AJUDA_URL=https://pt-br.facebook.com/www.abclivrosebrinquedos.com.br/
  web:
    stdin_open: true
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app
  nginx-proxy:
    depends_on:
      - api
      - web
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
